### ISSUE TITLE
PaizaのRubyのバージョンは、3.1.2

### ISSUE THREAD

**Issue by universato** [magurofly/atcoder-easy-test#22]
> Test Environment Ruby (2.7.1) [PaizaIO]

と表示されていますが、実際には3.1.2です。
他の言語はわからないですが、PaizaのRubyの更新はマメなように思います。

なお、Rubyのメジャー・マイナーのバージョンアップは、毎年クリスマス頃ですので、
来春には3.2.xになっているのではないかと思われます。

【paiza】paizaプログラミングスキルチェックの各言語のバージョン
 https://paiza.jp/guide/language

**Comment by magurofly** [comment]
情報ありがとうございます。
今週末くらいに更新したいと思っています（もしかすると、定期的にバージョンを取得しておく、というのも手かもしれませんね）

**Comment by magurofly** [comment]
バージョンを取得する API があるようですが、 `Access-Control-Allow-Origin: *` みたいなヘッダはないので、バージョンを取得するのはちょっと難し目かもしれないですね…（手作業でアップデートか…）

```js
fetch("https://paiza.io/api/runners/api_get_versions", { headers: { accept: "application/json" } }).then(res => res.json())
```

**Comment by magurofly** [comment]
（バージョン番号を表示せず、 paiza.io のヘルプを見てもらうという方法もありそうな気がしました。）

**Comment by universato** [comment]
AtCoderの問題を練習で解いてるときにeasy testでACだったのにAtCoderでWAになって「あれ、バージョンが違うんだろうな」ってなって、
easy testのバージョンを確かめたときに「あれ? ほぼ同じ2.7?」ってなったので一応Issueたてた感じです。

マイナーバージョンまでしっかり表示するように対応するのは大変だと思うので、
表示上「3.x」にしたり、paizaのヘルプへのリンクをつけたり、そのぐらいで十分そうな気はしました。

**Comment by magurofly** [comment]
以下の二つの対応を行うことにしました。
1. バージョンに関する情報をへらすことにします。ただし、AtCoder の言語の選択でバージョンが書いてあるようなものは 3.x とか 3 とか大まかなバージョンは表記します
2. README.md に paiza へのリンクを貼ることとします

**Comment by magurofly** [comment]
今回はpaiza.ioのもののみ対応を行います
Wandboxについてはまた別の話（バージョンの更新によってAPIも変化する）のため別途対応（するかも？）
