### ISSUE TITLE
CodeForcesの入力例や出力例では改行を正しく読み込めていますか？

### ISSUE THREAD

**Issue by hiro1729** [magurofly/atcoder-easy-test#33]

**Comment by magurofly** [comment]
この問題では読めているようです
https://codeforces.com/contest/1861/problem/A

読めていない例があれば教えていただけると幸いです

**Comment by magurofly** [comment]
ありがとうございます！
見てみると改行が`<br>`になっているのが原因のようなので、`<br>`を改行にするようにしてみます。

**Comment by magurofly** [comment]
うまくいってそう
