### ISSUE TITLE
Test Environmentが保存されない

### ISSUE THREAD

**Issue by strangerxxxx** [magurofly/atcoder-easy-test#38]
Chrome環境ではTest Environmentが保存されなくなっています。
(Firefox環境では保存されることを確認しています)

少し調べてみたのですが、下記の`eLanguage.addEventListener`がChrome環境では動いていないと思います。
https://github.com/magurofly/atcoder-easy-test/blob/1dbb75f03ae2b923b74ab6464a63951c8221ba41/v2/atcoder-easy-test.user.js#L2276-L2281

**Comment by hotate29** [comment]
手元のFirefox環境でも保存されない（changeイベントが発火しない）ことがあるようです。環境を変更する度に「getElementById()に空文字列が渡されました」というjQuery1.9.1（Easy Testが直接使っているjQueryとは異なるバージョン）からの警告がコンソールに出るのですが、何か関係しているのかもしれません。

保存される（changeイベントが発火する）こともあるのですが、条件が分からず再現できていません。

**Comment by strangerxxxx** [comment]
そもそもselect2に置き換わるのは意図しているものですかね？

https://github.com/magurofly/atcoder-easy-test/blob/1dbb75f03ae2b923b74ab6464a63951c8221ba41/v2/atcoder-easy-test.user.js#L2174
上記で
`<select class=\"form-control\" id=\"atcoder-easy-test-language\" style=\"width: 100% !important\">`
とベタ書きしてあるのですが、ブラウザ上では
`class="form-control select2-hidden-accessible"`
に置き換わってしまい、下部にchange2のフォームができるのが不思議に思っているので。

**Comment by magurofly** [comment]
検証ありがとうございます。
select2に置き換わってしまうのは全く意図していない挙動ですが、修正方法がわからないので今後の課題とします。
→jQuery経由でイベントリスナを登録することで一旦解決としました。（#46）
