### ISSUE TITLE
Python(PyPy)でWandboxの環境が表示されない

### ISSUE THREAD

**Issue by strangerxxxx** [magurofly/atcoder-easy-test#50]
v2.12.0で言語をPythonまたはPyPyにしたときに、Wandboxのテスト環境が表示されなくなっています。
おそらくですがAtCoder Easy Test上のkeyはPython3で、Wandbox APIでは"language":"Python"となっているせいですかね。
一応856行目を
`5055: "Python Python3 CPython 3.11.4",`
のように変えると表示はされるようになるのですが、いかにも応急的な感じなのと逆にAtCoder/Wandbox以外は表示されなくなるのでイマイチかなと……

**Comment by strangerxxxx** [comment]
よく考えたらこう変更すればいいですかね。
```javascript
fetchWandboxCompilers().then((compilers) => {
    for (const compiler of compilers) {
        if (compiler.name.startsWith('cpython') || compiler.name.startsWith('pypy')) {
            compiler.language = 'Python3';
        };
        const key = compiler.language + " " + compiler.name;
        runners[key] = toRunner(compiler);
        console.log("wandbox", key, runners[key]);
    }
});
```

**Comment by magurofly** [comment]
Issueありがとうございます。
そんな感じに解決させていただこうと思います。
